/** Queue names shared by producers and the worker. */
export const QUEUES = {
  connectionTest: 'connection.test',
  mailFetch: 'mail.fetch',
  mailProcess: 'mail.process',
  mailSend: 'mail.send',
  kbIngest: 'kb.ingest',
  followup: 'followup.generate',
  healthCheck: 'connection.health',
  tenantDelete: 'tenant.delete',
  quotesImport: 'quotes.import',
  documentsPrefill: 'documents.prefill',
  documentsAutomation: 'documents.automation',
  composeAssist: 'compose.assist',
  assistantTurn: 'assistant.turn',
  calendarSync: 'calendar.sync',
  calendarDisconnect: 'calendar.disconnect',
  bookingsConfirm: 'bookings.confirm',
  bookingsCancel: 'bookings.cancel',
  shopifyTest: 'shopify.test',
  shopifyDisconnect: 'shopify.disconnect',
  woocommerceTest: 'woocommerce.test',
  woocommerceDisconnect: 'woocommerce.disconnect',
} as const;
